### ISSUE TITLE
[DOCS] describe YAML import/export function

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1718]
Explain the format
```
version: 1.3.1
exportedAt: 2023-05-04T06:35:30.721Z
config:
  exportPrinters: true
  exportFloorGrid: true
  printerComparisonStrategiesByPriority:
    - name
    - url
  exportFloors: true
  floorComparisonStrategiesByPriority: floor
  notes: 'Some notes, made this layout for the summer 23'' setup '
printers:
  - id: 645351fe98d304b62a03e50d
    stepSize: 10
    enabled: true
    dateAdded: 1683182078022
    settingsAppearance:
      name: Relieved Forehead
    webSocketURL: ws://localhost/
    printerURL: http://localhost/
    apiKey: YOUR_API_KEY_HERE
floors:
  - id: 64427f2d070a27047acd5e6e
    floor: 1
    name: Default Floor
    printers:
      - printerId: 645351fe98d304b62a03e50d
        x: 1
        'y': 0
```

Show the UI
![image](https://user-images.githubusercontent.com/6005355/236128664-7bc576bd-4ac7-4acd-bf90-3acbcc354cf2.png)

Show the import
![image](https://user-images.githubusercontent.com/6005355/236128719-01fef3a0-4698-4321-9694-1e343b577277.png)
