### ISSUE TITLE
Failed to connect printer on docker-compose localhost

### ISSUE THREAD

**Issue by amrsoll** [fdm-monster/fdm-monster#2491]
**Describe the bug**

I tried to test FDM by running an Octorpint instance on localhost together with FDM.

I tried adding the OctoPrint instance on localhost

I get ` [API Exception Handler] Error: connect ECONNREFUSED 127.0.0.1:80`

**To Reproduce**

1. copy `docker-componse.yaml` here

```yaml
version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${YOUR_ROOT_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${YOUR_ROOT_PASSWORD}
    ports:
      - "28017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - ./mongoconfig:/data/configdb
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - MONGO=mongodb://${YOUR_ROOT_NAME}:${YOUR_ROOT_PASSWORD}@mongodb:27017/fdm-monster?authSource=admin
    volumes:
      - ./fdm-monster/media:/app/media

  octoprint:
    image: docker.io/octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
     - octoprint:/octoprint
```

2.  `YOUR_ROOT_NAME=root YOUR_ROOT_PASSWORD='12345678' docker-compose up`
3.  go to localhost and do the first OctoPrint setup + create an API key
4. Copy API key
5. go to `localhost:4000`
6. Go through 1st time setup
7. create printer using the API key + address `localhost`

**Expected behavior**

> Printer would connect

**Screenshots**

![20231020_17h17m23s_grim](https://github.com/fdm-monster/fdm-monster/assets/24782867/bd89b1a6-6a36-42a1-ad8e-eae8d5f7421e)

**Browser (please complete the following information):**
 - OS: Linux (NixOS / docker)
 - Browser Firefox
 - Version 1.5.0 

**Additional context**

**Comment by amrsoll** [comment]
might be related to #2181, is it not in the latest stable?

**Comment by davidzwa** [comment]
Hi,

Thanks for the bug report. I am also seeing inconsistencies sometimes. Mostly around `octopi.local` mDNS, but it is clear from your case more is going wrong and further investigation/mitigation is needed. 

Just to be sure, what OS are you running on? Are you able to resolve 127.0.0.1, 0.0.0.0, octoprint and/or host.docker.internal as alternative hostnames? 
This might help me track this problem down. 

Also, there's a timeout setting in the settings. This could help, but only partially (I still have to expose the websocket connection setting as well). 

About URL normalization yeah its merged a while ago. Especially for this reason to be honest. It resulted in the current form (on the UI side), which does not split up port and hostname anymore.

I hope you're up to test any fixes or testing elements for this issue that I will implement.

Thanks again!

**Comment by amrsoll** [comment]
Hi David,

Thank you for taking the time :D

It could be an issue with my setup, which is why i provided the docker compose to easily recreate fdm + octoprint on the same instance

I had also tried 127.0.0.1 with the same result

Running with docker compose on Nixos.

**Comment by amrsoll** [comment]
I tried the following with no luck

- connection timeout 1000 -> 5000 ms, no change (socket aborts instantly)
- http://127.0.0.1 -- http://0.0.0.0 -- http://localhost

I am able to connect to octoprint through the browser to all these addresses. Now I'm wondering if the issue lies in `docker-compose.yaml` in case the containers are not able to communicate between them. It would surprise me given that the mongo server doesn't have any special treatment.

**Comment by davidzwa** [comment]
I've tried to reproduce your setup.

```
... previous part was practically the same as yours ... 

  octoprint1234:
    image: docker.io/octoprint/octoprint
    restart: unless-stopped
    ports:
      - 800:80
    volumes:
     - octoprint1234:/octoprint

volumes:
  octoprint1234:
```

Indeed I cannot resolve 0.0.0.0 or 127.0.0.1 (same as localhost) with the test connection method, which tests it from within the FDM Monster container.

I am able to resolve:
- `octoprint1234:80` which is the same as `octoprint1234` - octoprint1234 is a valid hostname inside a docker network
![image](https://github.com/fdm-monster/fdm-monster/assets/6005355/e32c259f-f79f-4cd8-9e75-9f2d07d766da)
- `host.docker.internal:800` - with the external docker-compose port, personally I set it to 800
![image](https://github.com/fdm-monster/fdm-monster/assets/6005355/c4b40116-c50f-486b-8858-8bbec65eb856)
- `172.20.0.2` - this IP address is what docker auto-assigned to my OctoPrint container. Of course that's not very helpful, but I had to check for the purpose of elimination.
![image](https://github.com/fdm-monster/fdm-monster/assets/6005355/7a8f36e0-c67b-455c-a185-18ef4952e035)


I will do one quick experiment to check whether the server setup of FDM Monster can make a difference, because the FDM Monster NodeJS setup is bound to 0.0.0.0 inside the container. Maybe that changes things:
![image](https://github.com/fdm-monster/fdm-monster/assets/6005355/b5e29703-7c56-4871-bba0-400d8b07dc5d)
