### ISSUE TITLE
Unable to change password or modify user roles

### ISSUE THREAD

**Issue by callanova** [fdm-monster/fdm-monster#3464]
**Describe the bug**
When navigating to http://localhost:4000/settings/account, it states:
```
Login is currently disabled. To adjust your username and password, please enable that setting at the Server Protection settings page. Then log in and visit this page.
```
Within http://localhost:4000/settings/server-protection, Login Required > Require Login checkbox is enabled.
If a user registers a new account, I can verify the account via http://localhost:4000/settings/user-management and set it as a owner. However, the new account still has the GUEST role. When I login as that new account, I get "Permission Denied" message with the following (The problematic API path varies):
```
You do not have permission to access a specific resource on this page.
Page: Home
Usable roles: OPERATOR, ADMIN
Problematic API path: /api/printer
Error: Authorization failed
```
I'm unable to modify the roles to remove GUEST or add OPERATOR.

**To Reproduce**
> Create a docker-compose.yaml file with the following contents:
```
services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      # Authenticated variant, comment out for non-authenticated variant:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=fdm-root
    ports:
      - "28017:27017"
    volumes:
      - ./mongodb-data:/data/db
      - ./mongoconfig:/data/configdb
    restart: always

  fdm-monster:
    container_name: fdm-monster
    image: fdmmonster/fdm-monster:1.6.3
    restart: always
    ports:
      - "4000:4000"
    environment:
      # Authenticated variant:
      - MONGO=mongodb://root:fdm-root@mongodb:27017/fdm-monster?authSource=admin
      - SERVER_PORT=4000
    volumes:
      - ./fdm-monster/media/:/app/media

```
> Run `docker-compose up -d`
> Navigate to http://localhost:4000/ in a non private browser
> Go through the initial setup and enable Registration
> Log in with the account that was created
> Open a private browser
> Go through the steps to register a new account
> Navigate to http://localhost:4000/settings/user-management that is logged in with initial account
> Verify the new user
> Try to modify the user's Roles
> Try to modify the password for either account at http://localhost:4000/settings/account
**Expected behavior**
> Able to modify user Roles
> Able to change password

**Screenshots**
> 
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/9848cfaf-365a-4a4a-826a-0f55f73a50e2">
> 
<img width="1914" alt="image" src="https://github.com/user-attachments/assets/d5b73227-7987-49a5-a56a-b490b3b0b00f">
> 
<img width="1911" alt="image" src="https://github.com/user-attachments/assets/bfb80d74-f373-4505-a8e4-76d0f8e7205e">
> 
<img width="1912" alt="image" src="https://github.com/user-attachments/assets/33ef1809-0eef-4b35-908f-73c24df21e13">

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version:
 ```
Current versions in use:
Your server's version is: 1.6.3
Your client's version is: 1.5.14
```

**Additional context**

>
